// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaSach.Data;

#nullable disable

namespace QuanLyNhaSach.Migrations
{
    [DbContext(typeof(QuanLyBanSachContext))]
    [Migration("20260527073134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaDonHang", "MaSanPham")
                        .HasName("PK__CHI_TIET__DD39F0EFE69F097B");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_CHI_TIET_DON_HANG_MaSanPham");

                    b.ToTable("CHI_TIET_DON_HANG", null, t =>
                        {
                            t.HasTrigger("TRG_CapNhatKho_KhiBanHang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang", "MaSanPham")
                        .HasName("PK__CHI_TIET__3AAC69E1267D00E0");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_CHI_TIET_GIO_HANG_MaSanPham");

                    b.ToTable("CHI_TIET_GIO_HANG", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([SoLuong]*[GiaNhap])", true);

                    b.HasKey("MaPhieuNhap", "MaSanPham")
                        .HasName("PK__CHI_TIET__DBDC9B79BAF31BB4");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_PHIEU_NHAP", null, t =>
                        {
                            t.HasTrigger("TRG_CapNhatKho_KhiNhapHang");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DANH_GIA__AA9515BF00FF78FF");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_DANH_GIA_MaSanPham");

                    b.HasIndex(new[] { "MaNguoiDung", "MaSanPham" }, "UQ_DANH_GIA_NguoiDung_SanPham")
                        .IsUnique();

                    b.ToTable("DANH_GIA", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DANH_MUC__B3750887FFD3FCA9");

                    b.HasIndex("MaDanhMucCha");

                    b.ToTable("DANH_MUC", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DuongGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaXaGiao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PhiShip")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SoNhaGiao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DON_HANG__129584ADF0632E74");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex(new[] { "MaNguoiDung" }, "IX_DON_HANG_MaNguoiDung");

                    b.HasIndex(new[] { "MaXaGiao" }, "IX_DON_HANG_MaXaGiao");

                    b.HasIndex(new[] { "NgayDat" }, "IX_DON_HANG_NgayDat");

                    b.ToTable("DON_HANG", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaGioHang")
                        .HasName("PK__GIO_HANG__F5001DA34471A290");

                    b.HasIndex(new[] { "MaNguoiDung" }, "UQ_GIO_HANG_Active")
                        .IsUnique()
                        .HasFilter("([TrangThai]=(1))");

                    b.ToTable("GIO_HANG", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal?>("DieuKienApDung")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KHUYEN_M__6F56B3BD39408103");

                    b.ToTable("KHUYEN_MAI", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Duong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int?>("MaXa")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NGUOI_DU__C539D7620B43E353");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "MaXa" }, "IX_NGUOI_DUNG_MaXa");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NGUOI_DU__0389B7BDA6B0A6DB")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NGUOI_DU__A9D10534D8682603")
                        .IsUnique();

                    b.ToTable("NGUOI_DUNG", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NHA_CUNG__53DA92057A66061F");

                    b.ToTable("NHA_CUNG_CAP", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNhaXuatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaXuatBan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("MaNhaXuatBan")
                        .HasName("PK__NHA_XUAT__1AED0BFAF5993CD2");

                    b.ToTable("NHA_XUAT_BAN", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PHIEU_NH__1470EF3B0592846B");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("PHIEU_NHAP", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("AnhBia")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaBia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhaXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaSanPham")
                        .HasName("PK__SAN_PHAM__FAC7442D488C7ED5");

                    b.HasIndex(new[] { "MaDanhMuc" }, "IX_SAN_PHAM_MaDanhMuc");

                    b.HasIndex(new[] { "MaNhaXuatBan" }, "IX_SAN_PHAM_MaNhaXuatBan");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.TacGia", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaTacGia")
                        .HasName("PK__TAC_GIA__F24E675636A84915");

                    b.ToTable("TAC_GIA", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__THANH_TO__D4B258442397542D");

                    b.HasIndex(new[] { "MaDonHang" }, "UQ_THANH_TOAN_MaDonHang")
                        .IsUnique();

                    b.HasIndex(new[] { "MaGiaoDich" }, "UQ__THANH_TO__0A2A24EA95D752CF")
                        .IsUnique()
                        .HasFilter("[MaGiaoDich] IS NOT NULL");

                    b.ToTable("THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.TinhThanh", b =>
                {
                    b.Property<int>("MaTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinh"));

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaTinh")
                        .HasName("PK__TINH_THA__4CC54480865F2FE2");

                    b.ToTable("TINH_THANH", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.VDonHangDiaChi", b =>
                {
                    b.Property<string>("DiaChiGiaoDayDu")
                        .IsRequired()
                        .HasMaxLength(356)
                        .HasColumnType("nvarchar(356)");

                    b.Property<string>("DuongGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("SoNhaGiao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("V_DON_HANG_DIA_CHI", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.VNguoiDungDiaChi", b =>
                {
                    b.Property<string>("DiaChiDayDu")
                        .IsRequired()
                        .HasMaxLength(356)
                        .HasColumnType("nvarchar(356)");

                    b.Property<string>("Duong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("V_NGUOI_DUNG_DIA_CHI", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VAI_TRO__C24C41CF00E3B467");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VAI_TRO__1DA558149F0B0052")
                        .IsUnique();

                    b.ToTable("VAI_TRO", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.XaPhuong", b =>
                {
                    b.Property<int>("MaXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXa"));

                    b.Property<int>("MaTinh")
                        .HasColumnType("int");

                    b.Property<string>("TenXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaXa")
                        .HasName("PK__XA_PHUON__272520C9C6F8E3AA");

                    b.HasIndex("MaTinh");

                    b.ToTable("XA_PHUONG", (string)null);
                });

            modelBuilder.Entity("SanPhamTacGium", b =>
                {
                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("MaTacGia")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham", "MaTacGia")
                        .HasName("PK__SAN_PHAM__85E3A258F1EC2E3E");

                    b.HasIndex("MaTacGia");

                    b.ToTable("SAN_PHAM_TAC_GIA", (string)null);
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaDon__7A672E12");

                    b.HasOne("QuanLyNhaSach.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaSan__7B5B524B");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaGio__6EF57B66");

                    b.HasOne("QuanLyNhaSach.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaSan__6FE99F9F");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.PhieuNhap", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaPhi__1DB06A4F");

                    b.HasOne("QuanLyNhaSach.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaSan__1EA48E88");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DanhGium", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DANH_GIA__MaNguo__02FC7413");

                    b.HasOne("QuanLyNhaSach.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__DANH_GIA__MaSanP__03F0984C");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DanhMuc", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.DanhMuc", "MaDanhMucChaNavigation")
                        .WithMany("InverseMaDanhMucChaNavigation")
                        .HasForeignKey("MaDanhMucCha")
                        .HasConstraintName("FK__DANH_MUC__MaDanh__5441852A");

                    b.Navigation("MaDanhMucChaNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DonHang", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK__DON_HANG__MaKhuy__75A278F5");

                    b.HasOne("QuanLyNhaSach.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DON_HANG__MaNguo__72C60C4A");

                    b.HasOne("QuanLyNhaSach.Models.XaPhuong", "MaXaGiaoNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaXaGiao")
                        .HasConstraintName("FK_DON_HANG_XA_PHUONG");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaXaGiaoNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.GioHang", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithOne("GioHang")
                        .HasForeignKey("QuanLyNhaSach.Models.GioHang", "MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__GIO_HANG__MaNguo__693CA210");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK__NGUOI_DUN__MaVai__5070F446");

                    b.HasOne("QuanLyNhaSach.Models.XaPhuong", "MaXaNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaXa")
                        .HasConstraintName("FK_NGUOI_DUNG_XA_PHUONG");

                    b.Navigation("MaVaiTroNavigation");

                    b.Navigation("MaXaNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__PHIEU_NHA__MaNgu__18EBB532");

                    b.HasOne("QuanLyNhaSach.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .IsRequired()
                        .HasConstraintName("FK__PHIEU_NHA__MaNha__19DFD96B");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.SanPham", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__SAN_PHAM__MaDanh__5FB337D6");

                    b.HasOne("QuanLyNhaSach.Models.NhaXuatBan", "MaNhaXuatBanNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhaXuatBan")
                        .HasConstraintName("FK__SAN_PHAM__MaNhaX__60A75C0F");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNhaXuatBanNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.DonHang", "MaDonHangNavigation")
                        .WithOne("ThanhToan")
                        .HasForeignKey("QuanLyNhaSach.Models.ThanhToan", "MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__THANH_TOA__MaDon__7F2BE32F");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.XaPhuong", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.TinhThanh", "MaTinhNavigation")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("MaTinh")
                        .IsRequired()
                        .HasConstraintName("FK__XA_PHUONG__MaTin__0C85DE4D");

                    b.Navigation("MaTinhNavigation");
                });

            modelBuilder.Entity("SanPhamTacGium", b =>
                {
                    b.HasOne("QuanLyNhaSach.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SAN_PHAM___MaSan__656C112C");

                    b.HasOne("QuanLyNhaSach.Models.TacGia", null)
                        .WithMany()
                        .HasForeignKey("MaTacGia")
                        .IsRequired()
                        .HasConstraintName("FK__SAN_PHAM___MaTac__66603565");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DanhMuc", b =>
                {
                    b.Navigation("InverseMaDanhMucChaNavigation");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHang");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.NhaXuatBan", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.TinhThanh", b =>
                {
                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyNhaSach.Models.XaPhuong", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
